<a href="https://colab.research.google.com/github/LearningMore555/DeepLearningCode/blob/main/FirstColab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Fundamentals about PyTotch2023.6.11

Resource notebook: https://www.learnpytorch.io/

PyTorch documentaion: https://pytorch.org/docs/1.7.1/index.html
https://pytorch.org/docs/2.0/ 

In [1]:
print("Hello!Google!")
!nvidia-smi

Hello!Google!
Tue Jun 13 00:22:12 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   65C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                          

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.1+cu118


## Introduction to Tensors

Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/generated/torch.tensor.html#torch.tensor

In [20]:
# scalar
scalar = torch.tensor(7)
scalar1 = torch.tensor([7])

print(scalar.ndim)
print(scalar1.ndim)
print(scalar.shape)
print(scalar1.shape)

0
1
torch.Size([])
torch.Size([1])


In [7]:
scalar.ndim

0

In [8]:
# Get tensor back as Python int.
scalar.item()

7

In [24]:
# Vectoor
vector = torch.tensor([7, 7])
vector1 = torch.tensor([7, 7, 7])
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [25]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


In [37]:
# TENSOR
# In the book(https://www.learnpytorch.io/00_pytorch_fundamentals/), it says 
# scalar and vector use lower case, while MATRIX and TENSOR use upper case.
TENSOR = torch.tensor([[[1, 2],
                        [3, 4],
                        [5, 6]]])

print(TENSOR[0, 1])
print(TENSOR.shape)
print(TENSOR.ndim)

tensor(2)
torch.Size([1, 3, 2])
3


### Random tensors

Why random tensors?

Random tensors are important because the way that many neural networks learn is that they start with tensors full of random numbers and then adjust the random numbers to better represent the data. 

`start with random numbers -> look at data -> update random numbers -> look at data ->update random numbers -> ...`

`torch.rand()` = https://pytorch.org/docs/stable/generated/torch.rand.html

In [42]:
# Create a random tensor of size of (3, 4)
random_tensor = torch.rand(3, 4)
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape) 

tensor([[0.7054, 0.8781, 0.8816, 0.1462],
        [0.9290, 0.9846, 0.4786, 0.2421],
        [0.4698, 0.3634, 0.9680, 0.4242]])
2
torch.Size([3, 4])


### Zeros and ones

In [43]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
print(zeros*random_tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [44]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
print(ones.dtype)

torch.float32


### Creating a range of tensors and tensors-like

In [52]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
print(one_to_ten)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [53]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into witn PyTorch & Deep Learning: 
1. Tensors not right datatype;
2. Tensors not right shape;
3. Tensors not right device.

In [67]:
# Float 32 tensor
f32_tensor = torch.tensor([7, 1], 
                          dtype=torch.float32, # Data type of the tensor(e.g. float32, float64...)
                          device=None, # "cpu" or "cuda"
                          requires_grad=None)

# https://pytorch.org/docs/stable/tensors.html?highlight=torch+tensor#torch.Tensor
print(f32_tensor.dtype)

torch.float32


In [68]:
f16_tensor = f32_tensor.type(torch.float16)
print(f16_tensor.dtype)

torch.float16


### Getting information from tensors(tensor attributes)

1. `tensor.dtype`;
2. `tensor.shape`;
3. `tensor.device`;

(tensor function)
4. `tensor.size()`;
5. `tensor.type()`.

`torch.rand()` returns a tensor that contains random numbers drawn from the uniform distibution. While `torch.randn()` returns a tensor that contains random numbers drawn from normal distribution.

`torch.rand()` - https://pytorch.org/docs/stable/generated/torch.randn.html

`torch.randn()` - https://pytorch.org/docs/stable/generated/torch.randn.html

In [72]:
some_tensor = torch.rand(3, 4, device="cuda")
print(some_tensor.dtype, some_tensor.shape, some_tensor.device)
print(some_tensor.type(), some_tensor.size())

torch.float32 torch.Size([3, 4]) cuda:0
torch.cuda.FloatTensor torch.Size([3, 4])


### Manipulating Tensors (tensor  operations)

Teensor operations include: 
* Addition: `+`
* Subtraciton: `-`
* Multiplication(element-wise): `*`
* Division: `/`
* Matrix multiplitcation: `torch.matmul()` or `torch.mm()` for short - https://pytorch.org/docs/stable/generated/torch.matmul.html?highlight=torch+matmul#torch.matmul

There are two rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match;
2. The resulting matrix has the shape of the **outer dimensions**


In [79]:
# Create a tensor

%%time
tensor_1 = torch.rand(3, 4)
tensor_2 = torch.rand(4, 3)

print(tensor_1)
print(tensor_2)
print(torch.matmul(tensor_1, tensor_2))

tensor([[0.5658, 0.8853, 0.1216, 0.4169],
        [0.6045, 0.8269, 0.4622, 0.0743],
        [0.0022, 0.0933, 0.5924, 0.0506]])
tensor([[0.9581, 0.3538, 0.5936],
        [0.4743, 0.9292, 0.7034],
        [0.4281, 0.1981, 0.2340],
        [0.3095, 0.3559, 0.0626]])
tensor([[1.1431, 1.1953, 1.0131],
        [1.1922, 1.1003, 1.0532],
        [0.3156, 0.2228, 0.2087]])
CPU times: user 3.62 ms, sys: 0 ns, total: 3.62 ms
Wall time: 3.63 ms


**Transpose:** `.T` 

In [82]:
print(tensor_1.T)

tensor([[0.5658, 0.6045, 0.0022],
        [0.8853, 0.8269, 0.0933],
        [0.1216, 0.4622, 0.5924],
        [0.4169, 0.0743, 0.0506]])
