<a href="https://colab.research.google.com/github/LearningMore555/DeepLearningCode/blob/main/FirstColab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Fundamentals about PyTotch2023.6.11

Resource notebook: https://www.learnpytorch.io/

PyTorch documentaion: https://pytorch.org/docs/1.7.1/index.html
https://pytorch.org/docs/2.0/

In [1]:
print("Hello!Google!")
!nvidia-smi

Hello!Google!
Thu Jun 15 01:25:24 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   60C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                          

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.1+cu118


## Introduction to Tensors

Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/generated/torch.tensor.html#torch.tensor

In [3]:
# scalar
scalar = torch.tensor(7)
scalar1 = torch.tensor([7])

print(scalar.ndim)
print(scalar1.ndim)
print(scalar.shape)
print(scalar1.shape)

0
1
torch.Size([])
torch.Size([1])


In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int.
scalar.item()

7

In [6]:
# Vectoor
vector = torch.tensor([7, 7])
vector1 = torch.tensor([7, 7, 7])
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [7]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


In [8]:
# TENSOR
# In the book(https://www.learnpytorch.io/00_pytorch_fundamentals/), it says
# scalar and vector use lower case, while MATRIX and TENSOR use upper case.
TENSOR = torch.tensor([[[1, 2],
                        [3, 4],
                        [5, 6]]])

print(TENSOR[0, 1])
print(TENSOR.shape)
print(TENSOR.ndim)

tensor([3, 4])
torch.Size([1, 3, 2])
3


### Random tensors

Why random tensors?

Random tensors are important because the way that many neural networks learn is that they start with tensors full of random numbers and then adjust the random numbers to better represent the data.

`start with random numbers -> look at data -> update random numbers -> look at data ->update random numbers -> ...`

`torch.rand()` = https://pytorch.org/docs/stable/generated/torch.rand.html

In [9]:
# Create a random tensor of size of (3, 4)
random_tensor = torch.rand(3, 4)
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)

tensor([[0.6003, 0.3925, 0.4462, 0.9435],
        [0.3285, 0.9716, 0.2744, 0.8626],
        [0.7997, 0.3555, 0.6470, 0.9886]])
2
torch.Size([3, 4])


### Zeros and ones

In [10]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
print(zeros*random_tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [11]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
print(ones.dtype)

torch.float32


### Creating a range of tensors and tensors-like

In [12]:
# Use torch.arange() - https://pytorch.org/docs/stable/generated/torch.arange.html?highlight=torch+arange#torch.arange
one_to_ten = torch.arange(start=1, end=11, step=1)
print(one_to_ten)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [13]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into witn PyTorch & Deep Learning:
1. Tensors not right datatype;
2. Tensors not right shape;
3. Tensors not right device.

In [15]:
# Float 32 tensor
f32_tensor = torch.tensor([7, 1],
                          dtype=torch.float32, # Data type of the tensor(e.g. float32, float64...)
                          device=None, # "cpu" or "cuda"
                          requires_grad=False)

# https://pytorch.org/docs/stable/tensors.html?highlight=torch+tensor#torch.Tensor
print(f32_tensor.dtype)

torch.float32


In [16]:
f16_tensor = f32_tensor.type(torch.float16)
print(f16_tensor.dtype)

torch.float16


### Getting information from tensors(tensor attributes)

1. `tensor.dtype`;
2. `tensor.shape`;
3. `tensor.device`;

(tensor function)
4. `tensor.size()`;
5. `tensor.type()`.

`torch.rand()` returns a tensor that contains random numbers drawn from the uniform distibution. While `torch.randn()` returns a tensor that contains random numbers drawn from normal distribution.

`torch.rand()` - https://pytorch.org/docs/stable/generated/torch.randn.html

`torch.randn()` - https://pytorch.org/docs/stable/generated/torch.randn.html

In [17]:
some_tensor = torch.rand(3, 4, device="cuda")
print(some_tensor.dtype, some_tensor.shape, some_tensor.device)
print(some_tensor.type(), some_tensor.size())

torch.float32 torch.Size([3, 4]) cuda:0
torch.cuda.FloatTensor torch.Size([3, 4])


### Manipulating Tensors (tensor  operations)

Teensor operations include:
* Addition: `+`
* Subtraciton: `-`
* Multiplication(element-wise): `*`
* Division: `/`
* Matrix multiplitcation: `torch.matmul()` or `torch.mm()` for short - https://pytorch.org/docs/stable/generated/torch.matmul.html?highlight=torch+matmul#torch.matmul

There are two rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match;
2. The resulting matrix has the shape of the **outer dimensions**


In [18]:
# Create a tensor

%%time
tensor_1 = torch.rand(3, 4)
tensor_2 = torch.rand(4, 3)

print(tensor_1)
print(tensor_2)
print(torch.matmul(tensor_1, tensor_2))

tensor([[0.1203, 0.7948, 0.0620, 0.0915],
        [0.5889, 0.2017, 0.7990, 0.0017],
        [0.4242, 0.5789, 0.0791, 0.2828]])
tensor([[0.5312, 0.5487, 0.0862],
        [0.7711, 0.2405, 0.2899],
        [0.4511, 0.5583, 0.1886],
        [0.5474, 0.3194, 0.9750]])
tensor([[0.7548, 0.3210, 0.3418],
        [0.8298, 0.8183, 0.2616],
        [0.8622, 0.5065, 0.4950]])
CPU times: user 3.5 ms, sys: 789 µs, total: 4.29 ms
Wall time: 13.8 ms


**Transpose:** `.T`

In [20]:
print(tensor_1.T)

tensor([[0.1203, 0.5889, 0.4242],
        [0.7948, 0.2017, 0.5789],
        [0.0620, 0.7990, 0.0791],
        [0.0915, 0.0017, 0.2828]])


## Finding the min, max, mean, sum, etc(tensor  aggregation)
* min: `torch.min()` or `Name.min()`;
* max: `torch.max()` or `Name.max()`;
* mean: `torch.mean()` or `Name.mean()`;
* sum: `torch.sum()` or `Name.sum()`.

Note that `torch.mean()` or `Name.mean()` needs the element of the tensor to be float instead of long or int.

In [19]:
import torch
x = torch.rand(2, 4, 3)
# print(x)

In [21]:
torch.mean(x)
x.type(torch.float32)

print(x.dtype)

print(torch.mean(x), x.mean())
print(torch.min(x), x.min())
print(torch.max(x), x.max())
print(torch.sum(x), x.sum())

torch.float32
tensor(0.5388) tensor(0.5388)
tensor(0.1337) tensor(0.1337)
tensor(0.9207) tensor(0.9207)
tensor(12.9304) tensor(12.9304)


## Finding the positional min and max
* `Name.argmin()`: returns the position where the minimal value occurs in the target tensor.
* `Name.argmax()`: similar with `Name.argmin()` except it is for max value.

In [22]:
print(x.argmin())
print(x.argmax())

# Some extra exploriment.
t = torch.zeros(2, 3, 3)
t[0, 0, 0] = 1
t[0, 0, 1] = 1
print((t == 1).nonzero())

t1 = torch.zeros(2, 3, 3, 4)
t1[0, 0, 0, 0] = 1
t1[0, 1, 0, 1] = 1
print((t1==1).nonzero())
print((t1==1).nonzero(as_tuple=True))


tensor(12)
tensor(14)
tensor([[0, 0, 0],
        [0, 0, 1]])
tensor([[0, 0, 0, 0],
        [0, 1, 0, 1]])
(tensor([0, 0]), tensor([0, 1]), tensor([0, 0]), tensor([0, 1]))


## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshape - reshape an input tensor to a defined shape;

  `torch.reshape()` or `Name.reshape()` - https://pytorch.org/docs/stable/generated/torch.reshape.html?highlight=torch+reshape#torch.reshape

* View - return a view of an input tnesor of certain shape but keep the same memory as the orihinal tensor;

  `torch.Tensor.view()` - https://pytorch.org/docs/stable/generated/torch.Tensor.view.html?highlight=torch+view#torch.Tensor.view

  `torch.stride()` - https://pytorch.org/docs/stable/generated/torch.Tensor.stride.html
* Stacking - combine multiple tensors on toop of each other(vstack) or side by side(hstack)

  `torch.stack()` - https://pytorch.org/docs/stable/generated/torch.stack.html

  `torch.vstack()` - https://pytorch.org/docs/stable/generated/torch.vstack.html

  `torch.hstack()` - https://pytorch.org/docs/stable/generated/torch.hstack.html

* Squeeze - removes all `1` dimensions from a tensor;
* Unsqueeze -add a `1` dimension to a target tensor;
* Permute - return a view of the input with dimensions permuted(swapped) in a certain way.

In [2]:
# Create a tensor
import torch

print(type(1))
print(type(1.))
x = torch.arange(1., 10., 1.)
print(x, x.shape)

<class 'int'>
<class 'float'>
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])


In [ ]:
print(torch.reshape(x, (3, 3)))
print(x.reshape(3, 3))
print(x.reshape(1, 1, 9))
print(x.reshape(9, 1, 1))
print(x.reshape(1, 9, 1))

In [6]:
# Change the view.torch.view() doesn't create new tensor, it shares the same
# memory with the original tensor, but outputs a different shape. So if you change the view, the original
# tensor will also be changed.
import torch

x = torch.rand(1, 2, 3)
y = x.view(1, 3, 2)
print(y)
print(x) # Here, we can see that x haven't been changed.
z = x.transpose(1, 2)
print(z)

tensor([[[0.4473, 0.5051],
         [0.3615, 0.1270],
         [0.5241, 0.9618]]])
tensor([[[0.4473, 0.5051, 0.3615],
         [0.1270, 0.5241, 0.9618]]])
tensor([[[0.4473, 0.1270],
         [0.5051, 0.5241],
         [0.3615, 0.9618]]])
